config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :image_sets
  resources :maps
  root "maps#index"
  get "/maps", to: "maps#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
Rails.application.routes.draw do
  resources :maps do
    get :image_sets, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :image_set
  has_many_attached :source
end

app/models/image_set.rb
class ImageSet < ApplicationRecord
  validates :typ, presence: true
  validates :color, presence: true
  belongs_to :map
  has_many :images
end

app/models/map.rb
class Map < ApplicationRecord
  validates :title, presence: true
  validates :lat, presence: true
  validates :lng, presence: true
  validates :zoom, presence: true
  has_many :image_sets
  has_many :overlays
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/image_sets_controller.rb
class ImageSetsController < ApplicationController
  before_action :set_image_set, only: %i[ show edit update destroy ]

  # GET /image_sets or /image_sets.json
  def index
    @image_sets = ImageSet.includes(:map).all
  end

  # GET /image_sets/1 or /image_sets/1.json
  def show
  end

  # GET /image_sets/new
  def new
    @image_set = ImageSet.new
  end

  # GET /image_sets/1/edit
  def edit
  end

  # POST /image_sets or /image_sets.json
  def create
    @image_set = ImageSet.new(image_set_params)

    respond_to do |format|
      if @image_set.save
        format.html { redirect_to image_set_url(@image_set), notice: "Image set was successfully created." }
        format.json { render :show, status: :created, location: @image_set }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_sets/1 or /image_sets/1.json
  def update
    respond_to do |format|
      if @image_set.update(image_set_params)
        format.html { redirect_to image_set_url(@image_set), notice: "Image set was successfully updated." }
        format.json { render :show, status: :ok, location: @image_set }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_sets/1 or /image_sets/1.json
  def destroy
    @image_set.destroy

    respond_to do |format|
      format.html { redirect_to image_sets_url, notice: "Image set was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_image_set
    @image_set = ImageSet.includes(:map).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def image_set_params
    params.require(:image_set).permit(:title, :typ, :color, :map_id)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]


  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
    @image = Image.find_by(id: params[:id])
    redirect_to images_path, notice: "Image not found." if !@image
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json


  def create
    if params[:image][:source].present?
      params[:image][:source].each do |file|
        if file.is_a?(ActionDispatch::Http::UploadedFile)
          @image = Image.new(image_params)
          @image.source = file
          require 'exifr/jpeg'
          @image.title = EXIFR::JPEG.new(file.path).model
          @image.lat = EXIFR::JPEG.new(file.path).gps.latitude
          @image.lng = EXIFR::JPEG.new(file.path).gps.longitude
          @image.rotation = EXIFR::JPEG.new(file.path).gps.image_direction
          @image.date = EXIFR::JPEG.new(file.path).date_time
          @image.uploadedBy = EXIFR::JPEG.new(file.path).artist
          @image.save
        end
      end
      redirect_to images_path, notice: "Images were successfully uploaded."
    else
      redirect_to new_image_path, alert: "Please select at least one file to upload."
    end
  end




  # def create
  #   @image = Image.new(image_params)
  #
  #   respond_to do |format|
  #     if @image.save
  #       format.html { redirect_to image_url(@image), notice: "Image was successfully created." }
  #       format.json { render :show, status: :created, location: @image }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @image.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to image_url(@image), notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = Image.find(params[:id])
  end






  # Only allow a list of trusted parameters through.
  def image_params
    params.require(:image).permit(:title, :lat, :lng, :rotation, :tag, :date, :uploadedBy, :image_set_id, :source =>[])
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  layout 'sidebar'
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  def index
    @maps = Map.all
  end
  def image_sets
    @image_sets = Map.find(params[:id]).image_sets
    respond_to do |format|
      format.json { render json: @image_sets }
    end
  end
  def show
  end

  def new
    @map = Map.new
  end

  def edit
  end

  def create
    @map = Map.new(map_params)
    if @map.save
      redirect_to @map
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @map.update(map_params)
      redirect_to maps_path, notice: 'Map was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @map = Map.find(params[:id])
    @map.destroy
    redirect_to maps_path
  end

  private
  def set_map
    @map = Map.find(params[:id])
  end

  def map_params
    params.require(:map).permit(:title, :lat, :lng, :zoom)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_sets_helper.rb
module ImageSetsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/overlays_helper.rb
module OverlaysHelper
end

app/views/image_sets/_form.html.erb
<%= form_with(model: image_set, remote: true) do |form| %>
  <% if image_set.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(image_set.errors.count, "error") %> prohibited this image_set from being saved:</h2>

      <ul>
        <% image_set.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :typ, style: "display: block" %>
    <%= form.text_field :typ  %>
  </div>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.select :color, options_for_select([["Red","#ff0000"], ["Green","#00ff00"], ["Blue","#0000ff"], ["Yellow","#ffff00"], ["Black","#000000"], ["White","#ffffff"]], selected: image_set.color), {include_blank: 'Select Color'} %>
  </div>

  <div>
    <%= form.label :map_id, style: "display: block" %>
    <%= form.select :map_id, options_from_collection_for_select(Map.all, :id, :title, image_set.map_id), {include_blank: 'Select Map'} %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/image_sets/_image_set.html.erb
<div id="<%= dom_id image_set %>">

  <p>
    <strong>Typ:</strong>
    <%= image_set.typ %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= image_set.color %>
  </p>

  <p>
    <strong>Map:</strong>
    <%= image_set.map.title %>
  </p>

</div>

app/views/image_sets/edit.html.erb
<h1>Editing image set</h1>

<%= render "form", image_set: @image_set %>

<br>

<div>
  <%= button_to 'Back', image_set_path, method: :get, class: 'btn btn-secondary', id: 'backButton' %>
  <%= button_to "Delete", @image_set, method: :delete %>
</div>

app/views/image_sets/index.html.erb
<div id="image_sets">
  <% @image_sets.group_by(&:map).each do |map, image_sets| %>
    <h2><%= map.title %></h2>
    <div style="display: flex; flex-direction: row; flex-wrap: wrap">
      <% image_sets.each do |image_set| %>
        <%= link_to image_set, style: 'color: black; text-decoration: none' do %>
          <div class="card" style="width: 200px; height: 200px; display: flex; justify-content: center; text-align: center; align-items: center; border: 3px solid <%= image_set.color %>; margin: 15px;">
            <%= image_set.typ %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>









<div style="position: absolute; top: 10px; right: 10px">
  <%= button_to 'New image set', new_image_set_path, method: :get, class: 'btn btn-primary custom-button' %>
</div>

app/views/image_sets/new.html.erb
<h1>New image set</h1>

<%= render "form", image_set: @image_set %>

<br>

app/views/image_sets/show.html.erb
<p style="color: green"><%= notice %></p>
<div style=" display: flex;position: absolute; top: 10px; right: 10px">
  <%= button_to 'Edit', edit_image_set_path(@image_set), method: :get, class: 'btn btn-primary custom-button' %>
</div>
<%= render @image_set %>

app/views/images/_form.html.erb
<%= form_with(model: image) do |form| %>
  <% if image.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :tag, style: "display: block" %>
    <%= form.text_field :tag %>
  </div>



  <div>
    <%= form.label :source, multiple: true, style: "display: block" %>
    <%= form.file_field :source, multiple: true, name: "image[source][]" %>

  </div>



  <div>
    <%= form.label :map_id, style: "display: block" %>
    <%= form.collection_select :map_id, Map.all, :id, :title, {include_blank: 'Select Map'}, {id: 'map_id'}  %>
  </div>

  <div>
    <%= form.label :image_set_id, style: "display: block" %>
    <%= form.select :image_set_id, options_from_collection_for_select(ImageSet.all, :id, :typ, image.image_set_id),{include_blank: 'Select ImageSet'},{id: 'image_set_id' ,disabled: true}  %>
  </div>



  <div>
    <%= form.submit %>
  </div>

<% end %>


<script src="https://cdn.jsdelivr.net/npm/exifr/dist/lite.umd.js"></script>
<!--<script src="https://cdn.jsdelivr.net/npm/exif-js"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.1/min/dropzone.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script type="module">







    document.querySelector("#map_id").addEventListener("change", function() {
        var imageSetSelect = document.querySelector("#image_set_id");
        if (this.value) {
            imageSetSelect.disabled = false;
        } else {
            imageSetSelect.disabled = true;
        }
    });

    $(document).ready(function() {
        $('#map_id').on('change', function() {
            var mapId = $(this).val();
            $.ajax({
                url: '/maps/' + mapId + '/image_sets',
                dataType: 'json',
                success: function(data) {
                    var imageSetSelect = $('#image_set_id');
                    imageSetSelect.empty();
                    imageSetSelect.append($('<option>', {
                        value: '',
                        text: 'Select Image Set'
                    }));
                    $.each(data, function(index, imageSet) {
                        imageSetSelect.append($('<option>', {
                            value: imageSet.id,
                            text: imageSet.typ
                        }));
                    });
                    imageSetSelect.prop('disabled', false);
                }
            });
        });
    });
</script>

app/views/images/_image.html.erb
<div id="<%= dom_id image %>">
  <p>
    <strong>Title:</strong>
    <%= image.title %>
  </p>

  <p>
    <strong>Lat:</strong>
    <%= image.lat %>
  </p>

  <p>
    <strong>Lng:</strong>
    <%= image.lng %>
  </p>

  <p>
    <strong>Rotation:</strong>
    <%= image.rotation %>
  </p>

  <p>
    <strong>Tag:</strong>
    <%= image.tag %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= image.date %>
  </p>

  <p>
    <strong>Source:</strong>
    <%= image.source %>
  </p>

  <p>
    <strong>Uploadedby:</strong>
    <%= image.uploadedBy %>
  </p>

  <p>
    <strong>Imagesets:</strong>
    <%= image.image_set_id %>
  </p>

</div>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Show this image", @image %> |
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Images</h1>

<div id="images">
  <% @images.each do |image| %>
    <%= render image %>
    <p>
      <%= link_to "Show this image", image %>
    </p>
  <% end %>
</div>

<%= link_to "New image", new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @image %>


<% @image.source.each do |source| %>
  <%= image_tag source, class: "img-responsive", style:"max-height:200px"%>
<% end %>



<div>
  <%= link_to "Edit this image", edit_image_path(@image) %> |
  <%= link_to "Back to images", images_path %>

  <%= button_to "Destroy this image", @image, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imgmap</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
<h1>ImageMap</h1>
<div id="sidebar" style="float: left">
  <%= render 'shared/sidebar' %>
</div>
<div id="main" style="margin-left: 200px">
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/sidebar.html.erb
<html>
<body>
<h1>ImageMap</h1>
<div id="sidebar" style="float: left">
  <%= render 'shared/sidebar' %>
</div>
<div id="main" style="margin-left: 200px">
  <%= yield %>
</div>

</body>
</html>

app/views/maps/edit.html.erb
<head>
  <%= stylesheet_link_tag 'style' %>
</head>
<div id="editContainer">
<div id="CardView">
  <%= form_with model: @map, url: map_path(@map), method: :patch do |form| %>
    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
      <% @map.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
      <%= form.hidden_field :lat, id: 'hidden_lat' %>
      <%= form.hidden_field :lng, id: 'hidden_lng' %>
      <%= form.hidden_field :zoom, id: 'hidden_zoom' %>
    </div>
    <div>
      <%= button_to 'Back', map_path, method: :get, class: 'btn btn-secondary', id: 'backButton' %>
      <%= button_to 'Destroy', map_path(@map), method: :delete, data: {
        turbo_confirm: "Are you sure?"
      }, class: 'btn btn-danger', id: 'deleteButton' %>
      <%= form.submit %>
    </div>
  <% end %>
</div>
<div id="editMap"></div>
</div>






<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyBbBMrnS3KrUYYoOJ_k9a8EoOFaicyxCAw&callback=initMap", defer: true %>
<script>
    function initMap() {
        var latLng = {lat: <%= @map.lat %>, lng: <%= @map.lng %>};
        var map = new google.maps.Map(document.getElementById('editMap'), {
            zoom: <%= @map.zoom %>,
            center: latLng
        });

        google.maps.event.addListener(map, 'center_changed', function() {
            var latLng = map.getCenter();
            document.getElementById('hidden_lat').value = latLng.lat();
            document.getElementById('hidden_lng').value = latLng.lng();
            document.getElementById('hidden_zoom').value = map.zoom;
        });

    }
</script>

app/views/maps/index.html.erb
<div>
  <h1>Maps</h1>
  <br>
  <div style="display: flex; flex-direction: row; flex-wrap: wrap">
    <% @maps.each do |map| %>
      <%= link_to map, style: 'color: black; text-decoration: none' do %>
        <div class="card" style="width: 200px; height: 200px; display: flex; justify-content: center; text-align: center; align-items: center; border: 3px solid black; margin: 15px;">
          <!-- card content goes here -->
          <%= map.title %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div style="position: absolute; top: 10px; right: 10px">
    <%= button_to 'New Map', new_map_path, method: :get, class: 'btn btn-primary custom-button' %>
  </div>
</div>

app/views/maps/new.html.erb
<%= form_with model: @map, url: maps_path do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <% @map.errors.full_messages_for(:title).each do |message| %>
    <div><%= message %></div>
  <% end %>
  <%= form.hidden_field :lat, id: 'hidden_lat' %>
  <%= form.hidden_field :lng, id: 'hidden_lng' %>
  <%= form.hidden_field :zoom, id: 'hidden_zoom' %>
  <%= form.submit %>
<% end %>

<div style="height: 90vh" id="map"></div>

<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyBbBMrnS3KrUYYoOJ_k9a8EoOFaicyxCAw&callback=initMap", defer: true %>
<script>
    function initMap() {
        var latLng = {lat: 46.9626369748068, lng: 8.425040772032764};
        var zoom = 9;
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: zoom,
            center: latLng
        });

        google.maps.event.addListener(map, 'center_changed', function() {
            var latLng = map.getCenter();
            document.getElementById('hidden_lat').value = latLng.lat();
            document.getElementById('hidden_lng').value = latLng.lng();
            document.getElementById('hidden_zoom').value = map.zoom;
            console.log("LAT: "+latLng.lat())
            console.log("LNG: "+latLng.lng())
        });

    }
</script>

app/views/maps/show.html.erb
<h1>
  <%= @map.title %>
</h1>
<div style=" display: flex;position: absolute; top: 10px; right: 10px">
  <%= button_to 'Edit', edit_map_path(@map), method: :get, class: 'btn btn-primary custom-button' %>

</div>

<div style="height: 85vh" id="map"></div>

<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyBbBMrnS3KrUYYoOJ_k9a8EoOFaicyxCAw&callback=initMap", defer: true %>
<script>
    var marker;
    var imageheight;
    var imagewidth;

    function initMap() {
        getMeta('<%= image_path("overlay.jpg") %>', (err, img) => {
            imageheight = img.naturalHeight;
            imagewidth = img.naturalWidth;

            console.log(imageheight);
            console.log(imagewidth);
        });

        var latLng = {lat: <%= @map.lat %>, lng: <%= @map.lng %>};
        const map = new google.maps.Map(document.getElementById("map"), {
            zoom: <%= @map.zoom %>,
            center: { lat: <%= @map.lat %>, lng: <%= @map.lng %> },
            minZoom: <%= @map.zoom %> -1,
            draggable: false,
        });


    }

    function resizeMarker(size) {
        var aspectRatio = imagewidth/imageheight
        console.log(aspectRatio)

        marker.setIcon({
            url: '<%= image_path("overlay.jpg") %>',
            scaledSize: new google.maps.Size( (imagewidth*size)/100 * aspectRatio,(imageheight*size)/100 * aspectRatio),
        });
    }

    const getMeta = (url, cb) => {
        const img = new Image();
        img.onload = () => cb(null, img);
        img.onerror = (err) => cb(err);
        img.src = url;
    };



</script>

app/views/overlays/index.html.erb
<h1>Overlays#index</h1>
<p>Find me in app/views/overlays/index.html.erb</p>

app/views/shared/_sidebar.html.erb
<ul>
  <li><%= link_to "Maps", root_path %></li>
  <li><%= link_to "ImageSets", image_sets_path  %></li>
  <li><%= link_to "Images", images_path  %></li>
</ul>